application: nw-vsu
version: v2-4
runtime: python27
threadsafe: true
api_version: 1

inbound_services:
- mail

libraries:
- name: webapp2
  version: "latest"

handlers:

- url: /_ah/mail/admin.*
  script: admin.handlers
  login: admin

- url: /_ah/mail/update.*
  script: update.handlers
  login: admin

- url: /cron/.+
  script: cron.handlers
  login: admin

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: main.app